application: hushnote
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /lib
  static_dir: lib
  mime_type: application/javascript

- url: /.*
  script: hushnote.py
  secure: always
